
// This file has been generated by the GUI designer. Do not modify.
namespace Monsoon
{
	public partial class PreferencesDialog
	{
		private global::Gtk.Notebook prefNotebook;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Frame frame7;
		
		private global::Gtk.Alignment GtkAlignment10;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.ComboBox comboToolbarStyle;
		
		private global::Gtk.Label lblToolbarStyle;
		
		private global::Gtk.CheckButton loadDialogCheckButton;
		
		private global::Gtk.Label GtkLabel13;
		
		private global::Gtk.Frame frame8;
		
		private global::Gtk.Alignment GtkAlignment11;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.CheckButton enableNotificationsCheckButton;
		
		private global::Gtk.CheckButton enableTrayCheckButton;
		
		private global::Gtk.CheckButton minimizeTrayCheckButton;
		
		private global::Gtk.Label GtkLabel20;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Label maxConnectionsLabel;
		
		private global::Gtk.SpinButton maxConnectionsSpinButton;
		
		private global::Gtk.Label portLabel;
		
		private global::Gtk.SpinButton portSpinButton;
		
		private global::Gtk.CheckButton upnpCheckBox;
		
		private global::Gtk.Label GtkLabel5;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Table table4;
		
		private global::Gtk.Label downloadSpeedLabel;
		
		private global::Gtk.SpinButton maxDownloadSpeedSpinButton;
		
		private global::Gtk.SpinButton maxUploadSpeedSpinButton;
		
		private global::Gtk.Label uploadSpeedLabel;
		
		private global::Gtk.Label bandwidthPanelLabel;
		
		private global::Gtk.Frame frame9;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.ComboBox encryptionCombo;
		
		private global::Gtk.Label GtkLabel18;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.CheckButton startNewTorrentsCheckBox;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.Frame foldersFrame;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.Table foldersTable;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label GtkLabel8;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.CheckButton importTorrentsCheckBox;
		
		private global::Gtk.CheckButton removeOnImportCheckButton;
		
		private global::Gtk.HBox importDirectoryHbox;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label GtkLabel11;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Table table5;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.Label lblMaxActive;
		
		private global::Gtk.Label lblMaxDownload;
		
		private global::Gtk.Label lblMaxSeed;
		
		private global::Gtk.SpinButton spinMaxActive;
		
		private global::Gtk.SpinButton spinMaxDownload;
		
		private global::Gtk.SpinButton spinMaxSeed;
		
		private global::Gtk.Label labelActive;
		
		private global::Gtk.Label queuePage;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.Frame frame10;
		
		private global::Gtk.Alignment GtkAlignment6;
		
		private global::Gtk.HBox iconHbox;
		
		private global::Gtk.HBox iconEntryBox;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Entry nameEntry;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.VBox vbox12;
		
		private global::Gtk.Label GtkLabel19;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment7;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.ScrolledWindow labelScrolledWindow;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.Button addLabelButton;
		
		private global::Gtk.Button removeLabelButton;
		
		private global::Gtk.Label GtkLabel21;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Button button478;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Monsoon.PreferencesDialog
			this.Events = ((global::Gdk.EventMask)(256));
			this.Name = "Monsoon.PreferencesDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Monsoon Preferences");
			// Internal child Monsoon.PreferencesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Events = ((global::Gdk.EventMask)(256));
			w1.Name = "dialog_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog_VBox.Gtk.Box+BoxChild
			this.prefNotebook = new global::Gtk.Notebook ();
			this.prefNotebook.CanFocus = true;
			this.prefNotebook.Name = "prefNotebook";
			this.prefNotebook.CurrentPage = 0;
			// Container child prefNotebook.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment10 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment10.Name = "GtkAlignment10";
			this.GtkAlignment10.LeftPadding = ((uint)(12));
			// Container child GtkAlignment10.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboToolbarStyle = global::Gtk.ComboBox.NewText ();
			this.comboToolbarStyle.Name = "comboToolbarStyle";
			this.table1.Add (this.comboToolbarStyle);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboToolbarStyle]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblToolbarStyle = new global::Gtk.Label ();
			this.lblToolbarStyle.Name = "lblToolbarStyle";
			this.lblToolbarStyle.Xalign = 0F;
			this.lblToolbarStyle.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.table1.Add (this.lblToolbarStyle);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblToolbarStyle]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.loadDialogCheckButton = new global::Gtk.CheckButton ();
			this.loadDialogCheckButton.CanFocus = true;
			this.loadDialogCheckButton.Name = "loadDialogCheckButton";
			this.loadDialogCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enable Load Torrent confirmation dialog");
			this.loadDialogCheckButton.DrawIndicator = true;
			this.loadDialogCheckButton.UseUnderline = true;
			this.table1.Add (this.loadDialogCheckButton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.loadDialogCheckButton]));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment10.Add (this.table1);
			this.frame7.Add (this.GtkAlignment10);
			this.GtkLabel13 = new global::Gtk.Label ();
			this.GtkLabel13.Name = "GtkLabel13";
			this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Display Options</b>");
			this.GtkLabel13.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel13;
			this.vbox3.Add (this.frame7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame7]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment11 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment11.Name = "GtkAlignment11";
			this.GtkAlignment11.LeftPadding = ((uint)(12));
			// Container child GtkAlignment11.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.enableNotificationsCheckButton = new global::Gtk.CheckButton ();
			this.enableNotificationsCheckButton.CanFocus = true;
			this.enableNotificationsCheckButton.Name = "enableNotificationsCheckButton";
			this.enableNotificationsCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enable notifications on torrent completion");
			this.enableNotificationsCheckButton.DrawIndicator = true;
			this.enableNotificationsCheckButton.UseUnderline = true;
			this.table2.Add (this.enableNotificationsCheckButton);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.enableNotificationsCheckButton]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.enableTrayCheckButton = new global::Gtk.CheckButton ();
			this.enableTrayCheckButton.CanFocus = true;
			this.enableTrayCheckButton.Name = "enableTrayCheckButton";
			this.enableTrayCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enable icon");
			this.enableTrayCheckButton.DrawIndicator = true;
			this.enableTrayCheckButton.UseUnderline = true;
			this.table2.Add (this.enableTrayCheckButton);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.enableTrayCheckButton]));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.minimizeTrayCheckButton = new global::Gtk.CheckButton ();
			this.minimizeTrayCheckButton.CanFocus = true;
			this.minimizeTrayCheckButton.Name = "minimizeTrayCheckButton";
			this.minimizeTrayCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Minimize to notification area on close");
			this.minimizeTrayCheckButton.DrawIndicator = true;
			this.minimizeTrayCheckButton.UseUnderline = true;
			this.table2.Add (this.minimizeTrayCheckButton);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.minimizeTrayCheckButton]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment11.Add (this.table2);
			this.frame8.Add (this.GtkAlignment11);
			this.GtkLabel20 = new global::Gtk.Label ();
			this.GtkLabel20.Name = "GtkLabel20";
			this.GtkLabel20.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Notification Area Icon</b>");
			this.GtkLabel20.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel20;
			this.vbox3.Add (this.frame8);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame8]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.prefNotebook.Add (this.vbox3);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.prefNotebook.SetTabLabel (this.vbox3, this.label2);
			this.label2.ShowAll ();
			// Container child prefNotebook.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.maxConnectionsLabel = new global::Gtk.Label ();
			this.maxConnectionsLabel.Name = "maxConnectionsLabel";
			this.maxConnectionsLabel.Xalign = 0F;
			this.maxConnectionsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum connections: ");
			this.table3.Add (this.maxConnectionsLabel);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.maxConnectionsLabel]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.maxConnectionsSpinButton = new global::Gtk.SpinButton (0, 1000, 1);
			this.maxConnectionsSpinButton.CanFocus = true;
			this.maxConnectionsSpinButton.Name = "maxConnectionsSpinButton";
			this.maxConnectionsSpinButton.Adjustment.PageIncrement = 10;
			this.maxConnectionsSpinButton.ClimbRate = 1;
			this.maxConnectionsSpinButton.Numeric = true;
			this.table3.Add (this.maxConnectionsSpinButton);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.maxConnectionsSpinButton]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.portLabel = new global::Gtk.Label ();
			this.portLabel.Name = "portLabel";
			this.portLabel.Xalign = 0F;
			this.portLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Listen port: ");
			this.table3.Add (this.portLabel);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.portLabel]));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.portSpinButton = new global::Gtk.SpinButton (0, 65535, 1);
			this.portSpinButton.CanFocus = true;
			this.portSpinButton.Name = "portSpinButton";
			this.portSpinButton.Adjustment.PageIncrement = 10;
			this.portSpinButton.ClimbRate = 1;
			this.portSpinButton.Numeric = true;
			this.table3.Add (this.portSpinButton);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.portSpinButton]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.upnpCheckBox = new global::Gtk.CheckButton ();
			this.upnpCheckBox.CanFocus = true;
			this.upnpCheckBox.Name = "upnpCheckBox";
			this.upnpCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Enable UPnP");
			this.upnpCheckBox.DrawIndicator = true;
			this.upnpCheckBox.UseUnderline = true;
			this.table3.Add (this.upnpCheckBox);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.upnpCheckBox]));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table3);
			this.frame1.Add (this.GtkAlignment1);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ports</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel5;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.downloadSpeedLabel = new global::Gtk.Label ();
			this.downloadSpeedLabel.Name = "downloadSpeedLabel";
			this.downloadSpeedLabel.Xalign = 0F;
			this.downloadSpeedLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum download speed: ");
			this.table4.Add (this.downloadSpeedLabel);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table4 [this.downloadSpeedLabel]));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.maxDownloadSpeedSpinButton = new global::Gtk.SpinButton (0, 5000, 1);
			this.maxDownloadSpeedSpinButton.CanFocus = true;
			this.maxDownloadSpeedSpinButton.Name = "maxDownloadSpeedSpinButton";
			this.maxDownloadSpeedSpinButton.Adjustment.PageIncrement = 10;
			this.maxDownloadSpeedSpinButton.ClimbRate = 1;
			this.maxDownloadSpeedSpinButton.Numeric = true;
			this.table4.Add (this.maxDownloadSpeedSpinButton);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table4 [this.maxDownloadSpeedSpinButton]));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.maxUploadSpeedSpinButton = new global::Gtk.SpinButton (0, 5000, 1);
			this.maxUploadSpeedSpinButton.CanFocus = true;
			this.maxUploadSpeedSpinButton.Name = "maxUploadSpeedSpinButton";
			this.maxUploadSpeedSpinButton.Adjustment.PageIncrement = 10;
			this.maxUploadSpeedSpinButton.ClimbRate = 1;
			this.maxUploadSpeedSpinButton.Numeric = true;
			this.table4.Add (this.maxUploadSpeedSpinButton);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table4 [this.maxUploadSpeedSpinButton]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.uploadSpeedLabel = new global::Gtk.Label ();
			this.uploadSpeedLabel.Name = "uploadSpeedLabel";
			this.uploadSpeedLabel.Xalign = 0F;
			this.uploadSpeedLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum upload speed: ");
			this.table4.Add (this.uploadSpeedLabel);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table4 [this.uploadSpeedLabel]));
			w26.TopAttach = ((uint)(1));
			w26.BottomAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table4);
			this.frame2.Add (this.GtkAlignment2);
			this.bandwidthPanelLabel = new global::Gtk.Label ();
			this.bandwidthPanelLabel.Name = "bandwidthPanelLabel";
			this.bandwidthPanelLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Bandwidth</b>");
			this.bandwidthPanelLabel.UseMarkup = true;
			this.frame2.LabelWidget = this.bandwidthPanelLabel;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0F, 0.5F, 1F, 0F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(12));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Encryption");
			this.hbox3.Add (this.label9);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label9]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.encryptionCombo = global::Gtk.ComboBox.NewText ();
			this.encryptionCombo.AppendText (global::Mono.Unix.Catalog.GetString ("No Encryption\r"));
			this.encryptionCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Allow Encryption\r"));
			this.encryptionCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Prefer Encryption\r"));
			this.encryptionCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Force Encryption"));
			this.encryptionCombo.Name = "encryptionCombo";
			this.encryptionCombo.Active = 1;
			this.hbox3.Add (this.encryptionCombo);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.encryptionCombo]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.alignment1.Add (this.hbox3);
			this.frame9.Add (this.alignment1);
			this.GtkLabel18 = new global::Gtk.Label ();
			this.GtkLabel18.Name = "GtkLabel18";
			this.GtkLabel18.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Encryption</b>");
			this.GtkLabel18.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel18;
			this.vbox2.Add (this.frame9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame9]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.prefNotebook.Add (this.vbox2);
			global::Gtk.Notebook.NotebookChild w35 = ((global::Gtk.Notebook.NotebookChild)(this.prefNotebook [this.vbox2]));
			w35.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Connection");
			this.prefNotebook.SetTabLabel (this.vbox2, this.label3);
			this.label3.ShowAll ();
			// Container child prefNotebook.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.startNewTorrentsCheckBox = new global::Gtk.CheckButton ();
			this.startNewTorrentsCheckBox.CanFocus = true;
			this.startNewTorrentsCheckBox.Name = "startNewTorrentsCheckBox";
			this.startNewTorrentsCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Start added torrents automatically");
			this.startNewTorrentsCheckBox.Active = true;
			this.startNewTorrentsCheckBox.DrawIndicator = true;
			this.startNewTorrentsCheckBox.UseUnderline = true;
			this.vbox8.Add (this.startNewTorrentsCheckBox);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.startNewTorrentsCheckBox]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			this.GtkAlignment5.Add (this.vbox8);
			this.frame4.Add (this.GtkAlignment5);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>General</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel7;
			this.vbox5.Add (this.frame4);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame4]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.foldersFrame = new global::Gtk.Frame ();
			this.foldersFrame.Name = "foldersFrame";
			this.foldersFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child foldersFrame.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.foldersTable = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.foldersTable.Name = "foldersTable";
			this.foldersTable.RowSpacing = ((uint)(6));
			this.foldersTable.ColumnSpacing = ((uint)(6));
			// Container child foldersTable.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Default download location: ");
			this.foldersTable.Add (this.label1);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.foldersTable [this.label1]));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child foldersTable.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Torrent storage location:");
			this.foldersTable.Add (this.label7);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.foldersTable [this.label7]));
			w41.TopAttach = ((uint)(1));
			w41.BottomAttach = ((uint)(2));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.foldersTable);
			this.foldersFrame.Add (this.GtkAlignment3);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Folders</b>");
			this.GtkLabel8.UseMarkup = true;
			this.foldersFrame.LabelWidget = this.GtkLabel8;
			this.vbox5.Add (this.foldersFrame);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.foldersFrame]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.importTorrentsCheckBox = new global::Gtk.CheckButton ();
			this.importTorrentsCheckBox.CanFocus = true;
			this.importTorrentsCheckBox.Name = "importTorrentsCheckBox";
			this.importTorrentsCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Import new torrents automatically");
			this.importTorrentsCheckBox.DrawIndicator = true;
			this.importTorrentsCheckBox.UseUnderline = true;
			this.vbox7.Add (this.importTorrentsCheckBox);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.importTorrentsCheckBox]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.removeOnImportCheckButton = new global::Gtk.CheckButton ();
			this.removeOnImportCheckButton.CanFocus = true;
			this.removeOnImportCheckButton.Name = "removeOnImportCheckButton";
			this.removeOnImportCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Remove torrent file after imported");
			this.removeOnImportCheckButton.DrawIndicator = true;
			this.removeOnImportCheckButton.UseUnderline = true;
			this.vbox7.Add (this.removeOnImportCheckButton);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.removeOnImportCheckButton]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.importDirectoryHbox = new global::Gtk.HBox ();
			this.importDirectoryHbox.Name = "importDirectoryHbox";
			this.importDirectoryHbox.Spacing = 6;
			// Container child importDirectoryHbox.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Import directory:");
			this.importDirectoryHbox.Add (this.label6);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.importDirectoryHbox [this.label6]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			this.vbox7.Add (this.importDirectoryHbox);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.importDirectoryHbox]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.GtkAlignment4.Add (this.vbox7);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel11 = new global::Gtk.Label ();
			this.GtkLabel11.Name = "GtkLabel11";
			this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Importing Torrents</b>");
			this.GtkLabel11.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel11;
			this.vbox5.Add (this.frame3);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame3]));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			this.prefNotebook.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w52 = ((global::Gtk.Notebook.NotebookChild)(this.prefNotebook [this.vbox5]));
			w52.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Downloads");
			this.prefNotebook.SetTabLabel (this.vbox5, this.label4);
			this.label4.ShowAll ();
			// Container child prefNotebook.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.BorderWidth = ((uint)(3));
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table5 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.table5.Add (this.alignment2);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table5 [this.alignment2]));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.lblMaxActive = new global::Gtk.Label ();
			this.lblMaxActive.Name = "lblMaxActive";
			this.lblMaxActive.Xalign = 0F;
			this.lblMaxActive.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.table5.Add (this.lblMaxActive);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table5 [this.lblMaxActive]));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.lblMaxDownload = new global::Gtk.Label ();
			this.lblMaxDownload.Name = "lblMaxDownload";
			this.lblMaxDownload.Xalign = 0F;
			this.lblMaxDownload.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.table5.Add (this.lblMaxDownload);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table5 [this.lblMaxDownload]));
			w55.TopAttach = ((uint)(1));
			w55.BottomAttach = ((uint)(2));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.lblMaxSeed = new global::Gtk.Label ();
			this.lblMaxSeed.Name = "lblMaxSeed";
			this.lblMaxSeed.Xalign = 0F;
			this.lblMaxSeed.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.table5.Add (this.lblMaxSeed);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table5 [this.lblMaxSeed]));
			w56.TopAttach = ((uint)(2));
			w56.BottomAttach = ((uint)(3));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.spinMaxActive = new global::Gtk.SpinButton (0, 100, 1);
			this.spinMaxActive.CanFocus = true;
			this.spinMaxActive.Name = "spinMaxActive";
			this.spinMaxActive.Adjustment.PageIncrement = 10;
			this.spinMaxActive.ClimbRate = 1;
			this.spinMaxActive.Numeric = true;
			this.table5.Add (this.spinMaxActive);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table5 [this.spinMaxActive]));
			w57.LeftAttach = ((uint)(2));
			w57.RightAttach = ((uint)(3));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.spinMaxDownload = new global::Gtk.SpinButton (0, 100, 1);
			this.spinMaxDownload.CanFocus = true;
			this.spinMaxDownload.Name = "spinMaxDownload";
			this.spinMaxDownload.Adjustment.PageIncrement = 10;
			this.spinMaxDownload.ClimbRate = 1;
			this.spinMaxDownload.Numeric = true;
			this.table5.Add (this.spinMaxDownload);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table5 [this.spinMaxDownload]));
			w58.TopAttach = ((uint)(1));
			w58.BottomAttach = ((uint)(2));
			w58.LeftAttach = ((uint)(2));
			w58.RightAttach = ((uint)(3));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.spinMaxSeed = new global::Gtk.SpinButton (0, 100, 1);
			this.spinMaxSeed.CanFocus = true;
			this.spinMaxSeed.Name = "spinMaxSeed";
			this.spinMaxSeed.Adjustment.PageIncrement = 10;
			this.spinMaxSeed.ClimbRate = 1;
			this.spinMaxSeed.Numeric = true;
			this.table5.Add (this.spinMaxSeed);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table5 [this.spinMaxSeed]));
			w59.TopAttach = ((uint)(2));
			w59.BottomAttach = ((uint)(3));
			w59.LeftAttach = ((uint)(2));
			w59.RightAttach = ((uint)(3));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table5);
			this.frame5.Add (this.GtkAlignment);
			this.labelActive = new global::Gtk.Label ();
			this.labelActive.Name = "labelActive";
			this.labelActive.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>frame1</b>");
			this.labelActive.UseMarkup = true;
			this.frame5.LabelWidget = this.labelActive;
			this.vbox4.Add (this.frame5);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame5]));
			w62.Position = 0;
			w62.Expand = false;
			w62.Fill = false;
			this.prefNotebook.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w63 = ((global::Gtk.Notebook.NotebookChild)(this.prefNotebook [this.vbox4]));
			w63.Position = 3;
			// Notebook tab
			this.queuePage = new global::Gtk.Label ();
			this.queuePage.Name = "queuePage";
			this.queuePage.LabelProp = global::Mono.Unix.Catalog.GetString ("Queue");
			this.prefNotebook.SetTabLabel (this.vbox4, this.queuePage);
			this.queuePage.ShowAll ();
			// Container child prefNotebook.Gtk.Notebook+NotebookChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame10 = new global::Gtk.Frame ();
			this.frame10.Name = "frame10";
			this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame10.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.iconHbox = new global::Gtk.HBox ();
			this.iconHbox.Name = "iconHbox";
			this.iconHbox.Spacing = 6;
			// Container child iconHbox.Gtk.Box+BoxChild
			this.iconEntryBox = new global::Gtk.HBox ();
			this.iconEntryBox.Name = "iconEntryBox";
			this.iconEntryBox.Spacing = 6;
			this.iconHbox.Add (this.iconEntryBox);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.iconHbox [this.iconEntryBox]));
			w64.Position = 0;
			// Container child iconHbox.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.nameEntry = new global::Gtk.Entry ();
			this.nameEntry.CanFocus = true;
			this.nameEntry.Name = "nameEntry";
			this.nameEntry.IsEditable = true;
			this.nameEntry.InvisibleChar = '●';
			this.hbox6.Add (this.nameEntry);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.nameEntry]));
			w65.PackType = ((global::Gtk.PackType)(1));
			w65.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.hbox6.Add (this.label8);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label8]));
			w66.PackType = ((global::Gtk.PackType)(1));
			w66.Position = 1;
			w66.Expand = false;
			w66.Fill = false;
			this.vbox10.Add (this.hbox6);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox6]));
			w67.Position = 0;
			w67.Expand = false;
			w67.Fill = false;
			this.iconHbox.Add (this.vbox10);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.iconHbox [this.vbox10]));
			w68.Position = 1;
			// Container child iconHbox.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			this.iconHbox.Add (this.vbox12);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.iconHbox [this.vbox12]));
			w69.Position = 2;
			this.GtkAlignment6.Add (this.iconHbox);
			this.frame10.Add (this.GtkAlignment6);
			this.GtkLabel19 = new global::Gtk.Label ();
			this.GtkLabel19.Name = "GtkLabel19";
			this.GtkLabel19.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Create a label</b>");
			this.GtkLabel19.UseMarkup = true;
			this.frame10.LabelWidget = this.GtkLabel19;
			this.vbox9.Add (this.frame10);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.frame10]));
			w72.Position = 0;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.labelScrolledWindow.CanFocus = true;
			this.labelScrolledWindow.Name = "labelScrolledWindow";
			this.labelScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.hbox8.Add (this.labelScrolledWindow);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.labelScrolledWindow]));
			w73.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.addLabelButton = new global::Gtk.Button ();
			this.addLabelButton.Sensitive = false;
			this.addLabelButton.CanFocus = true;
			this.addLabelButton.Name = "addLabelButton";
			this.addLabelButton.UseUnderline = true;
			this.addLabelButton.Label = global::Mono.Unix.Catalog.GetString ("Add");
			global::Gtk.Image w74 = new global::Gtk.Image ();
			w74.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.addLabelButton.Image = w74;
			this.vbox11.Add (this.addLabelButton);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.addLabelButton]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.removeLabelButton = new global::Gtk.Button ();
			this.removeLabelButton.Sensitive = false;
			this.removeLabelButton.CanFocus = true;
			this.removeLabelButton.Name = "removeLabelButton";
			this.removeLabelButton.UseUnderline = true;
			this.removeLabelButton.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			global::Gtk.Image w76 = new global::Gtk.Image ();
			w76.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.removeLabelButton.Image = w76;
			this.vbox11.Add (this.removeLabelButton);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.removeLabelButton]));
			w77.Position = 1;
			w77.Expand = false;
			w77.Fill = false;
			this.hbox8.Add (this.vbox11);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox11]));
			w78.Position = 1;
			w78.Expand = false;
			w78.Fill = false;
			this.GtkAlignment7.Add (this.hbox8);
			this.frame6.Add (this.GtkAlignment7);
			this.GtkLabel21 = new global::Gtk.Label ();
			this.GtkLabel21.Name = "GtkLabel21";
			this.GtkLabel21.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Manage labels</b>");
			this.GtkLabel21.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel21;
			this.vbox9.Add (this.frame6);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.frame6]));
			w81.Position = 1;
			this.prefNotebook.Add (this.vbox9);
			global::Gtk.Notebook.NotebookChild w82 = ((global::Gtk.Notebook.NotebookChild)(this.prefNotebook [this.vbox9]));
			w82.Position = 4;
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Labels");
			this.prefNotebook.SetTabLabel (this.vbox9, this.label10);
			this.label10.ShowAll ();
			w1.Add (this.prefNotebook);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(w1 [this.prefNotebook]));
			w83.Position = 0;
			// Internal child Monsoon.PreferencesDialog.ActionArea
			global::Gtk.HButtonBox w84 = this.ActionArea;
			w84.Name = "GtkDialog_ActionArea";
			w84.Spacing = 6;
			w84.BorderWidth = ((uint)(5));
			w84.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child GtkDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button478 = new global::Gtk.Button ();
			this.button478.CanDefault = true;
			this.button478.CanFocus = true;
			this.button478.Name = "button478";
			this.button478.UseStock = true;
			this.button478.UseUnderline = true;
			this.button478.Label = "gtk-close";
			this.AddActionWidget (this.button478, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w85 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w84 [this.button478]));
			w85.Expand = false;
			w85.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 445;
			this.DefaultHeight = 423;
			this.Show ();
			this.portSpinButton.ValueChanged += new global::System.EventHandler (this.OnPortSpinButtonValueChanged);
			this.maxConnectionsSpinButton.ValueChanged += new global::System.EventHandler (this.OnMaxConnectionsSpinButtonValueChanged);
			this.maxUploadSpeedSpinButton.ValueChanged += new global::System.EventHandler (this.OnMaxUploadSpeedSpinButtonValueChanged);
			this.maxDownloadSpeedSpinButton.ValueChanged += new global::System.EventHandler (this.OnMaxDownloadSpeedSpinButtonValueChanged);
			this.startNewTorrentsCheckBox.Clicked += new global::System.EventHandler (this.OnStartNewTorrentsCheckBoxClicked);
			this.importTorrentsCheckBox.Clicked += new global::System.EventHandler (this.OnImportTorrentsCheckBoxClicked);
			this.removeOnImportCheckButton.Clicked += new global::System.EventHandler (this.OnRemoveOnImportCheckButtonClicked);
			this.nameEntry.Changed += new global::System.EventHandler (this.OnNameEntryChanged);
			this.addLabelButton.Clicked += new global::System.EventHandler (this.OnAddLabelButtonClicked);
			this.removeLabelButton.Clicked += new global::System.EventHandler (this.OnRemoveLabelButtonClicked);
		}
	}
}
