
// This file has been generated by the GUI designer. Do not modify.
namespace Monsoon
{
	public partial class CreateTorrentDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox selectFileHbox;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.RadioButton fileRadioButton;
		
		private global::Gtk.RadioButton folderRadioButton;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Entry trackerEntry;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TreeView trackerTreeView;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Button addTrackerButton;
		
		private global::Gtk.Button removeTrackerButton;
		
		private global::Gtk.Label GtkLabel5;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry commentEntry;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.CheckButton startSeedingCheckBox;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.CheckButton hiddenFilesCheckBox;
		
		private global::Gtk.Label GtkLabel8;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Monsoon.CreateTorrentDialog
			this.Name = "Monsoon.CreateTorrentDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Create a torrent");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Monsoon.CreateTorrentDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.selectFileHbox = new global::Gtk.HBox ();
			this.selectFileHbox.Name = "selectFileHbox";
			this.selectFileHbox.Spacing = 6;
			// Container child selectFileHbox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Path:");
			this.selectFileHbox.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.selectFileHbox [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox5.Add (this.selectFileHbox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.selectFileHbox]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.fileRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Single File"));
			this.fileRadioButton.CanFocus = true;
			this.fileRadioButton.Name = "fileRadioButton";
			this.fileRadioButton.Active = true;
			this.fileRadioButton.DrawIndicator = true;
			this.fileRadioButton.UseUnderline = true;
			this.fileRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table1.Add (this.fileRadioButton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.fileRadioButton]));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.folderRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Folder"));
			this.folderRadioButton.CanFocus = true;
			this.folderRadioButton.Name = "folderRadioButton";
			this.folderRadioButton.DrawIndicator = true;
			this.folderRadioButton.UseUnderline = true;
			this.folderRadioButton.Group = this.fileRadioButton.Group;
			this.table1.Add (this.folderRadioButton);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.folderRadioButton]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox5.Add (this.table1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.table1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment2.Add (this.vbox5);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Select source</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.trackerEntry = new global::Gtk.Entry ();
			this.trackerEntry.CanFocus = true;
			this.trackerEntry.Name = "trackerEntry";
			this.trackerEntry.IsEditable = true;
			this.trackerEntry.InvisibleChar = '●';
			this.vbox3.Add (this.trackerEntry);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.trackerEntry]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.trackerTreeView = new global::Gtk.TreeView ();
			this.trackerTreeView.CanFocus = true;
			this.trackerTreeView.Name = "trackerTreeView";
			this.scrolledwindow1.Add (this.trackerTreeView);
			this.vbox3.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scrolledwindow1]));
			w12.Position = 1;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w13.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.addTrackerButton = new global::Gtk.Button ();
			this.addTrackerButton.Sensitive = false;
			this.addTrackerButton.CanFocus = true;
			this.addTrackerButton.Name = "addTrackerButton";
			this.addTrackerButton.UseUnderline = true;
			this.addTrackerButton.Label = global::Mono.Unix.Catalog.GetString ("Add");
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.addTrackerButton.Image = w14;
			this.vbox4.Add (this.addTrackerButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.addTrackerButton]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.removeTrackerButton = new global::Gtk.Button ();
			this.removeTrackerButton.Sensitive = false;
			this.removeTrackerButton.CanFocus = true;
			this.removeTrackerButton.Name = "removeTrackerButton";
			this.removeTrackerButton.UseUnderline = true;
			this.removeTrackerButton.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.removeTrackerButton.Image = w16;
			this.vbox4.Add (this.removeTrackerButton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.removeTrackerButton]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.GtkAlignment3.Add (this.hbox2);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Set a tracker</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel5;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w21.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Comment:");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.commentEntry = new global::Gtk.Entry ();
			this.commentEntry.CanFocus = true;
			this.commentEntry.Name = "commentEntry";
			this.commentEntry.IsEditable = true;
			this.commentEntry.InvisibleChar = '●';
			this.hbox4.Add (this.commentEntry);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.commentEntry]));
			w23.Position = 1;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.startSeedingCheckBox = new global::Gtk.CheckButton ();
			this.startSeedingCheckBox.CanFocus = true;
			this.startSeedingCheckBox.Name = "startSeedingCheckBox";
			this.startSeedingCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Start seeding");
			this.startSeedingCheckBox.Active = true;
			this.startSeedingCheckBox.DrawIndicator = true;
			this.startSeedingCheckBox.UseUnderline = true;
			this.hbox5.Add (this.startSeedingCheckBox);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.startSeedingCheckBox]));
			w25.Position = 0;
			this.vbox6.Add (this.hbox5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hiddenFilesCheckBox = new global::Gtk.CheckButton ();
			this.hiddenFilesCheckBox.CanFocus = true;
			this.hiddenFilesCheckBox.Name = "hiddenFilesCheckBox";
			this.hiddenFilesCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Ignore hidden files");
			this.hiddenFilesCheckBox.Active = true;
			this.hiddenFilesCheckBox.DrawIndicator = true;
			this.hiddenFilesCheckBox.UseUnderline = true;
			this.hbox6.Add (this.hiddenFilesCheckBox);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hiddenFilesCheckBox]));
			w27.Position = 0;
			this.vbox6.Add (this.hbox6);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.GtkAlignment4.Add (this.vbox6);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Miscellaneous</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel8;
			this.vbox2.Add (this.frame3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w32.Position = 0;
			// Internal child Monsoon.CreateTorrentDialog.ActionArea
			global::Gtk.HButtonBox w33 = this.ActionArea;
			w33.Name = "GtkDialog_ActionArea";
			w33.Spacing = 6;
			w33.BorderWidth = ((uint)(5));
			w33.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child GtkDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w33 [this.buttonCancel]));
			w34.Expand = false;
			w34.Fill = false;
			// Container child GtkDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w35 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w33 [this.buttonOk]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 403;
			this.DefaultHeight = 438;
			this.Show ();
			this.folderRadioButton.Toggled += new global::System.EventHandler (this.OnFolderRadioButtonToggled);
			this.fileRadioButton.Toggled += new global::System.EventHandler (this.OnFileRadioButtonToggled);
			this.trackerEntry.Changed += new global::System.EventHandler (this.OnTrackerEntryChanged);
			this.addTrackerButton.Clicked += new global::System.EventHandler (this.OnAddTrackerButtonClicked);
			this.removeTrackerButton.Clicked += new global::System.EventHandler (this.OnRemoveTrackerButtonClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnCreateButtonClicked);
		}
	}
}
