
// This file has been generated by the GUI designer. Do not modify.
namespace Monsoon
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action EditAction;
		
		private global::Gtk.Action ViewAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.Action About;
		
		private global::Gtk.Action Quit;
		
		private global::Gtk.Action stopTorrentButton;
		
		private global::Gtk.Action removeTorrentButton;
		
		private global::Gtk.Action preferences;
		
		private global::Gtk.Action deleteTorrentButton;
		
		private global::Gtk.Action EditColumns;
		
		private global::Gtk.ToggleAction ShowLabels;
		
		private global::Gtk.ToggleAction ShowDetailedInfo;
		
		private global::Gtk.Action OpenTorrent;
		
		private global::Gtk.Action startTorrentButton;
		
		private global::Gtk.Action NewTorrent;
		
		private global::Gtk.Action Plugins;
		
		private global::Gtk.Action ReportBugAction;
		
		private global::Gtk.Action gotoTopAction;
		
		private global::Gtk.Action gotoBottomAction;
		
		private global::Gtk.Action CloseAction;
		
		private global::Gtk.Action AddInManagerAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.Toolbar toolbar1;
		
		private global::Gtk.HPaned hPaned;
		
		private global::Gtk.ScrolledWindow labelViewScrolledWindow;
		
		private global::Gtk.VPaned vPaned;
		
		private global::Gtk.ScrolledWindow torrentViewScrolledWindow;
		
		private global::Gtk.Notebook detailNotebook;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label statusProgressBarLabel;
		
		private global::Gtk.ProgressBar statusProgressBar;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Table table8;
		
		private global::Gtk.Label downloadedValueLabel;
		
		private global::Gtk.Label elapsedTimeLabel;
		
		private global::Gtk.Label elapsedTimeValueLabel;
		
		private global::Gtk.Label hashFailsLabel;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label swarmSpeedLabel;
		
		private global::Gtk.Label uploadedValueLabel;
		
		private global::Gtk.Label GtkLabel6;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.Table table7;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label lastUpdatedLabel;
		
		private global::Gtk.Label messageLabel;
		
		private global::Gtk.Label trackerStatusValueLabel;
		
		private global::Gtk.Label trackerUrlValueLabel;
		
		private global::Gtk.Label updateInLabel;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Table table9;
		
		private global::Gtk.Label commentValueLabel;
		
		private global::Gtk.Label createdOnValueLabel;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label savePathValueLabel;
		
		private global::Gtk.Label sizeValueLabel;
		
		private global::Gtk.Label GtkLabel8;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow filesScrolledWindow;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.ScrolledWindow piecesScrolledWindow;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.ScrolledWindow peersScrolledWindow;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.SpinButton torrentDownloadRateSpinButton;
		
		private global::Gtk.SpinButton torrentMaxConnectionsSpinButton;
		
		private global::Gtk.SpinButton torrentUploadRateSpinButton;
		
		private global::Gtk.SpinButton torrentUploadSlotSpinButton;
		
		private global::Gtk.Label GtkLabel11;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Alignment alignment4;
		
		private global::Gtk.HBox hbox4;
		
		private global::Monsoon.NatWidget natStatus;
		
		private global::Gtk.Toolbar statusToolbar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Monsoon.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("_Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("_View"), null, null);
			this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
			w1.Add (this.ViewAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.About = new global::Gtk.Action ("About", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-about");
			this.About.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
			w1.Add (this.About, null);
			this.Quit = new global::Gtk.Action ("Quit", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
			this.Quit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.Quit, null);
			this.stopTorrentButton = new global::Gtk.Action ("stopTorrentButton", null, global::Mono.Unix.Catalog.GetString ("Stop the torrent"), "gtk-media-stop");
			this.stopTorrentButton.Sensitive = false;
			w1.Add (this.stopTorrentButton, null);
			this.removeTorrentButton = new global::Gtk.Action ("removeTorrentButton", null, global::Mono.Unix.Catalog.GetString ("Remove the torrent"), "gtk-remove");
			this.removeTorrentButton.Sensitive = false;
			w1.Add (this.removeTorrentButton, null);
			this.preferences = new global::Gtk.Action ("preferences", null, global::Mono.Unix.Catalog.GetString ("Open the preferences dialog"), "gtk-preferences");
			w1.Add (this.preferences, null);
			this.deleteTorrentButton = new global::Gtk.Action ("deleteTorrentButton", null, global::Mono.Unix.Catalog.GetString ("Remove the torrent and delete it's data"), "gtk-delete");
			this.deleteTorrentButton.Sensitive = false;
			w1.Add (this.deleteTorrentButton, null);
			this.EditColumns = new global::Gtk.Action ("EditColumns", global::Mono.Unix.Catalog.GetString ("Edit Columns"), null, null);
			this.EditColumns.ShortLabel = global::Mono.Unix.Catalog.GetString ("Columns");
			w1.Add (this.EditColumns, null);
			this.ShowLabels = new global::Gtk.ToggleAction ("ShowLabels", global::Mono.Unix.Catalog.GetString ("Show Labels"), null, null);
			this.ShowLabels.ShortLabel = global::Mono.Unix.Catalog.GetString ("Show Labels");
			w1.Add (this.ShowLabels, null);
			this.ShowDetailedInfo = new global::Gtk.ToggleAction ("ShowDetailedInfo", global::Mono.Unix.Catalog.GetString ("Show Detailed Info"), null, null);
			this.ShowDetailedInfo.ShortLabel = global::Mono.Unix.Catalog.GetString ("Show Detailed Info");
			w1.Add (this.ShowDetailedInfo, null);
			this.OpenTorrent = new global::Gtk.Action ("OpenTorrent", global::Mono.Unix.Catalog.GetString ("_Open Torrent"), global::Mono.Unix.Catalog.GetString ("Open existing torrent file"), "gtk-open");
			this.OpenTorrent.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open Torrent");
			w1.Add (this.OpenTorrent, null);
			this.startTorrentButton = new global::Gtk.Action ("startTorrentButton", null, global::Mono.Unix.Catalog.GetString ("Start the torrent"), "gtk-media-play");
			this.startTorrentButton.Sensitive = false;
			w1.Add (this.startTorrentButton, null);
			this.NewTorrent = new global::Gtk.Action ("NewTorrent", global::Mono.Unix.Catalog.GetString ("_New Torrent"), global::Mono.Unix.Catalog.GetString ("Create a new torrent"), "gtk-new");
			this.NewTorrent.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New Torrent");
			w1.Add (this.NewTorrent, null);
			this.Plugins = new global::Gtk.Action ("Plugins", global::Mono.Unix.Catalog.GetString ("Plugins"), global::Mono.Unix.Catalog.GetString ("Open the RSS manager"), "rss");
			this.Plugins.ShortLabel = global::Mono.Unix.Catalog.GetString ("Plugins");
			w1.Add (this.Plugins, null);
			this.ReportBugAction = new global::Gtk.Action ("ReportBugAction", global::Mono.Unix.Catalog.GetString ("Report Bug"), null, null);
			this.ReportBugAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Report Bug");
			w1.Add (this.ReportBugAction, null);
			this.gotoTopAction = new global::Gtk.Action ("gotoTopAction", null, null, "gtk-goto-top");
			w1.Add (this.gotoTopAction, null);
			this.gotoBottomAction = new global::Gtk.Action ("gotoBottomAction", null, null, "gtk-goto-bottom");
			w1.Add (this.gotoBottomAction, null);
			this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
			this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
			w1.Add (this.CloseAction, null);
			this.AddInManagerAction = new global::Gtk.Action ("AddInManagerAction", global::Mono.Unix.Catalog.GetString ("_Add-in Manager"), null, "gtk-properties");
			this.AddInManagerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Add-in Manager");
			w1.Add (this.AddInManagerAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Monsoon.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Monsoon");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_weather-showers", global::Gtk.IconSize.Dialog);
			// Container child Monsoon.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='NewTorrent' action='NewTorrent'/><menuitem name='OpenTorrent' action='OpenTorrent'/><separator/><menuitem name='CloseAction' action='CloseAction'/><menuitem name='Quit' action='Quit'/></menu><menu name='EditAction' action='EditAction'><menuitem name='AddInManagerAction' action='AddInManagerAction'/><menuitem name='preferences' action='preferences'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='EditColumns' action='EditColumns'/><separator/><menuitem name='ShowLabels' action='ShowLabels'/><menuitem name='ShowDetailedInfo' action='ShowDetailedInfo'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='About' action='About'/><menuitem name='ReportBugAction' action='ReportBugAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='NewTorrent' action='NewTorrent'/><toolitem name='OpenTorrent' action='OpenTorrent'/><separator/><toolitem name='startTorrentButton' action='startTorrentButton'/><toolitem name='stopTorrentButton' action='stopTorrentButton'/><toolitem name='removeTorrentButton' action='removeTorrentButton'/><toolitem name='deleteTorrentButton' action='deleteTorrentButton'/><separator/><toolitem name='gotoTopAction' action='gotoTopAction'/><toolitem name='gotoBottomAction' action='gotoBottomAction'/><separator/><toolitem name='Plugins' action='Plugins'/><toolitem name='preferences' action='preferences'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.vbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hPaned = new global::Gtk.HPaned ();
			this.hPaned.CanFocus = true;
			this.hPaned.Name = "hPaned";
			this.hPaned.Position = 145;
			// Container child hPaned.Gtk.Paned+PanedChild
			this.labelViewScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.labelViewScrolledWindow.CanFocus = true;
			this.labelViewScrolledWindow.Name = "labelViewScrolledWindow";
			this.hPaned.Add (this.labelViewScrolledWindow);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hPaned [this.labelViewScrolledWindow]));
			w4.Resize = false;
			// Container child hPaned.Gtk.Paned+PanedChild
			this.vPaned = new global::Gtk.VPaned ();
			this.vPaned.CanFocus = true;
			this.vPaned.Name = "vPaned";
			this.vPaned.Position = 165;
			// Container child vPaned.Gtk.Paned+PanedChild
			this.torrentViewScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.torrentViewScrolledWindow.CanFocus = true;
			this.torrentViewScrolledWindow.Name = "torrentViewScrolledWindow";
			this.torrentViewScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vPaned.Add (this.torrentViewScrolledWindow);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.vPaned [this.torrentViewScrolledWindow]));
			w5.Resize = false;
			// Container child vPaned.Gtk.Paned+PanedChild
			this.detailNotebook = new global::Gtk.Notebook ();
			this.detailNotebook.CanFocus = true;
			this.detailNotebook.Name = "detailNotebook";
			this.detailNotebook.CurrentPage = 4;
			// Container child detailNotebook.Gtk.Notebook+NotebookChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w6 = new global::Gtk.Viewport ();
			w6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(5));
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.statusProgressBarLabel = new global::Gtk.Label ();
			this.statusProgressBarLabel.Name = "statusProgressBarLabel";
			this.statusProgressBarLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Status: ");
			this.hbox3.Add (this.statusProgressBarLabel);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.statusProgressBarLabel]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.statusProgressBar = new global::Gtk.ProgressBar ();
			this.statusProgressBar.Name = "statusProgressBar";
			this.statusProgressBar.Text = global::Mono.Unix.Catalog.GetString (" ");
			this.hbox3.Add (this.statusProgressBar);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.statusProgressBar]));
			w8.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.WidthRequest = 260;
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table8 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table8.Name = "table8";
			this.table8.RowSpacing = ((uint)(6));
			this.table8.ColumnSpacing = ((uint)(6));
			// Container child table8.Gtk.Table+TableChild
			this.downloadedValueLabel = new global::Gtk.Label ();
			this.downloadedValueLabel.Name = "downloadedValueLabel";
			this.downloadedValueLabel.Xalign = 0F;
			this.table8.Add (this.downloadedValueLabel);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table8 [this.downloadedValueLabel]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.elapsedTimeLabel = new global::Gtk.Label ();
			this.elapsedTimeLabel.Name = "elapsedTimeLabel";
			this.elapsedTimeLabel.Xalign = 0F;
			this.elapsedTimeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Elapsed Time:");
			this.table8.Add (this.elapsedTimeLabel);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table8 [this.elapsedTimeLabel]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.elapsedTimeValueLabel = new global::Gtk.Label ();
			this.elapsedTimeValueLabel.Name = "elapsedTimeValueLabel";
			this.elapsedTimeValueLabel.Xalign = 0F;
			this.table8.Add (this.elapsedTimeValueLabel);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table8 [this.elapsedTimeValueLabel]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.hashFailsLabel = new global::Gtk.Label ();
			this.hashFailsLabel.Name = "hashFailsLabel";
			this.hashFailsLabel.Xalign = 0F;
			this.table8.Add (this.hashFailsLabel);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table8 [this.hashFailsLabel]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.Xalign = 0F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Downloaded:");
			this.table8.Add (this.label21);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table8 [this.label21]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 0F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Uploaded:");
			this.table8.Add (this.label22);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table8 [this.label22]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Hash Fails:");
			this.table8.Add (this.label3);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table8 [this.label3]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Swarm Speed:");
			this.table8.Add (this.label5);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table8 [this.label5]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.swarmSpeedLabel = new global::Gtk.Label ();
			this.swarmSpeedLabel.Name = "swarmSpeedLabel";
			this.swarmSpeedLabel.Xalign = 0F;
			this.table8.Add (this.swarmSpeedLabel);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table8 [this.swarmSpeedLabel]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.uploadedValueLabel = new global::Gtk.Label ();
			this.uploadedValueLabel.Name = "uploadedValueLabel";
			this.uploadedValueLabel.Xalign = 0F;
			this.table8.Add (this.uploadedValueLabel);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table8 [this.uploadedValueLabel]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table8);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Transfer</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel6;
			this.hbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame1]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table7 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Update In:");
			this.table7.Add (this.label19);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table7 [this.label19]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xalign = 0F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Status:");
			this.table7.Add (this.label20);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table7 [this.label20]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 0F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Message:");
			this.table7.Add (this.label23);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table7 [this.label23]));
			w25.TopAttach = ((uint)(4));
			w25.BottomAttach = ((uint)(5));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Last Updated:");
			this.table7.Add (this.label4);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table7 [this.label4]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("URL:");
			this.table7.Add (this.label8);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table7 [this.label8]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.lastUpdatedLabel = new global::Gtk.Label ();
			this.lastUpdatedLabel.Name = "lastUpdatedLabel";
			this.lastUpdatedLabel.Xalign = 0F;
			this.table7.Add (this.lastUpdatedLabel);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table7 [this.lastUpdatedLabel]));
			w28.TopAttach = ((uint)(2));
			w28.BottomAttach = ((uint)(3));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.messageLabel = new global::Gtk.Label ();
			this.messageLabel.Name = "messageLabel";
			this.messageLabel.Xalign = 0F;
			this.messageLabel.Wrap = true;
			this.table7.Add (this.messageLabel);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table7 [this.messageLabel]));
			w29.TopAttach = ((uint)(4));
			w29.BottomAttach = ((uint)(5));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.trackerStatusValueLabel = new global::Gtk.Label ();
			this.trackerStatusValueLabel.Name = "trackerStatusValueLabel";
			this.trackerStatusValueLabel.Xalign = 0F;
			this.table7.Add (this.trackerStatusValueLabel);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table7 [this.trackerStatusValueLabel]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.trackerUrlValueLabel = new global::Gtk.Label ();
			this.trackerUrlValueLabel.Name = "trackerUrlValueLabel";
			this.trackerUrlValueLabel.Xalign = 0F;
			this.table7.Add (this.trackerUrlValueLabel);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table7 [this.trackerUrlValueLabel]));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(2));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.updateInLabel = new global::Gtk.Label ();
			this.updateInLabel.Name = "updateInLabel";
			this.updateInLabel.Xalign = 0F;
			this.table7.Add (this.updateInLabel);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table7 [this.updateInLabel]));
			w32.TopAttach = ((uint)(3));
			w32.BottomAttach = ((uint)(4));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table7);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tracker</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel7;
			this.hbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame2]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table9 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table9.Name = "table9";
			this.table9.RowSpacing = ((uint)(6));
			this.table9.ColumnSpacing = ((uint)(6));
			// Container child table9.Gtk.Table+TableChild
			this.commentValueLabel = new global::Gtk.Label ();
			this.commentValueLabel.Name = "commentValueLabel";
			this.commentValueLabel.Xalign = 0F;
			this.table9.Add (this.commentValueLabel);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table9 [this.commentValueLabel]));
			w37.TopAttach = ((uint)(3));
			w37.BottomAttach = ((uint)(4));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.createdOnValueLabel = new global::Gtk.Label ();
			this.createdOnValueLabel.Name = "createdOnValueLabel";
			this.createdOnValueLabel.Xalign = 0F;
			this.table9.Add (this.createdOnValueLabel);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table9 [this.createdOnValueLabel]));
			w38.TopAttach = ((uint)(2));
			w38.BottomAttach = ((uint)(3));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Size:");
			this.table9.Add (this.label10);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table9 [this.label10]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Created on:");
			this.table9.Add (this.label11);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table9 [this.label11]));
			w40.TopAttach = ((uint)(2));
			w40.BottomAttach = ((uint)(3));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Comment:");
			this.table9.Add (this.label12);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table9 [this.label12]));
			w41.TopAttach = ((uint)(3));
			w41.BottomAttach = ((uint)(4));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Save path:");
			this.table9.Add (this.label7);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table9 [this.label7]));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.savePathValueLabel = new global::Gtk.Label ();
			this.savePathValueLabel.Name = "savePathValueLabel";
			this.savePathValueLabel.Xalign = 0F;
			this.table9.Add (this.savePathValueLabel);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table9 [this.savePathValueLabel]));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.sizeValueLabel = new global::Gtk.Label ();
			this.sizeValueLabel.Name = "sizeValueLabel";
			this.sizeValueLabel.Xalign = 0F;
			this.table9.Add (this.sizeValueLabel);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table9 [this.sizeValueLabel]));
			w44.TopAttach = ((uint)(1));
			w44.BottomAttach = ((uint)(2));
			w44.LeftAttach = ((uint)(1));
			w44.RightAttach = ((uint)(2));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table9);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>General</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel8;
			this.vbox4.Add (this.frame3);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame3]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			w6.Add (this.vbox4);
			this.scrolledwindow1.Add (w6);
			this.detailNotebook.Add (this.scrolledwindow1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.detailNotebook.SetTabLabel (this.scrolledwindow1, this.label1);
			this.label1.ShowAll ();
			// Container child detailNotebook.Gtk.Notebook+NotebookChild
			this.filesScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.filesScrolledWindow.CanFocus = true;
			this.filesScrolledWindow.Name = "filesScrolledWindow";
			this.filesScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.detailNotebook.Add (this.filesScrolledWindow);
			global::Gtk.Notebook.NotebookChild w51 = ((global::Gtk.Notebook.NotebookChild)(this.detailNotebook [this.filesScrolledWindow]));
			w51.Position = 1;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Files");
			this.detailNotebook.SetTabLabel (this.filesScrolledWindow, this.label9);
			this.label9.ShowAll ();
			// Container child detailNotebook.Gtk.Notebook+NotebookChild
			this.piecesScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.piecesScrolledWindow.CanFocus = true;
			this.piecesScrolledWindow.Name = "piecesScrolledWindow";
			this.piecesScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.detailNotebook.Add (this.piecesScrolledWindow);
			global::Gtk.Notebook.NotebookChild w52 = ((global::Gtk.Notebook.NotebookChild)(this.detailNotebook [this.piecesScrolledWindow]));
			w52.Position = 2;
			// Notebook tab
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Pieces");
			this.detailNotebook.SetTabLabel (this.piecesScrolledWindow, this.label18);
			this.label18.ShowAll ();
			// Container child detailNotebook.Gtk.Notebook+NotebookChild
			this.peersScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.peersScrolledWindow.CanFocus = true;
			this.peersScrolledWindow.Name = "peersScrolledWindow";
			this.peersScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.detailNotebook.Add (this.peersScrolledWindow);
			global::Gtk.Notebook.NotebookChild w53 = ((global::Gtk.Notebook.NotebookChild)(this.detailNotebook [this.peersScrolledWindow]));
			w53.Position = 3;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Peers");
			this.detailNotebook.SetTabLabel (this.peersScrolledWindow, this.label6);
			this.label6.ShowAll ();
			// Container child detailNotebook.Gtk.Notebook+NotebookChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w54 = new global::Gtk.Viewport ();
			w54.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport5.Gtk.Container+ContainerChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum upload rate:");
			this.table2.Add (this.label14);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table2 [this.label14]));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum download rate:");
			this.table2.Add (this.label15);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table2 [this.label15]));
			w56.TopAttach = ((uint)(1));
			w56.BottomAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum connections:");
			this.table2.Add (this.label16);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table2 [this.label16]));
			w57.TopAttach = ((uint)(2));
			w57.BottomAttach = ((uint)(3));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 0F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Upload slots:");
			this.table2.Add (this.label17);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table2 [this.label17]));
			w58.TopAttach = ((uint)(3));
			w58.BottomAttach = ((uint)(4));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.torrentDownloadRateSpinButton = new global::Gtk.SpinButton (0, 100, 1);
			this.torrentDownloadRateSpinButton.CanFocus = true;
			this.torrentDownloadRateSpinButton.Name = "torrentDownloadRateSpinButton";
			this.torrentDownloadRateSpinButton.Adjustment.PageIncrement = 10;
			this.torrentDownloadRateSpinButton.ClimbRate = 1;
			this.torrentDownloadRateSpinButton.Numeric = true;
			this.table2.Add (this.torrentDownloadRateSpinButton);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table2 [this.torrentDownloadRateSpinButton]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(1));
			w59.RightAttach = ((uint)(2));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.torrentMaxConnectionsSpinButton = new global::Gtk.SpinButton (0, 100, 1);
			this.torrentMaxConnectionsSpinButton.CanFocus = true;
			this.torrentMaxConnectionsSpinButton.Name = "torrentMaxConnectionsSpinButton";
			this.torrentMaxConnectionsSpinButton.Adjustment.PageIncrement = 10;
			this.torrentMaxConnectionsSpinButton.ClimbRate = 1;
			this.torrentMaxConnectionsSpinButton.Numeric = true;
			this.table2.Add (this.torrentMaxConnectionsSpinButton);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table2 [this.torrentMaxConnectionsSpinButton]));
			w60.TopAttach = ((uint)(2));
			w60.BottomAttach = ((uint)(3));
			w60.LeftAttach = ((uint)(1));
			w60.RightAttach = ((uint)(2));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.torrentUploadRateSpinButton = new global::Gtk.SpinButton (0, 100, 1);
			this.torrentUploadRateSpinButton.CanFocus = true;
			this.torrentUploadRateSpinButton.Name = "torrentUploadRateSpinButton";
			this.torrentUploadRateSpinButton.Adjustment.PageIncrement = 10;
			this.torrentUploadRateSpinButton.ClimbRate = 1;
			this.torrentUploadRateSpinButton.Numeric = true;
			this.table2.Add (this.torrentUploadRateSpinButton);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table2 [this.torrentUploadRateSpinButton]));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.torrentUploadSlotSpinButton = new global::Gtk.SpinButton (0, 100, 1);
			this.torrentUploadSlotSpinButton.CanFocus = true;
			this.torrentUploadSlotSpinButton.Name = "torrentUploadSlotSpinButton";
			this.torrentUploadSlotSpinButton.Adjustment.PageIncrement = 10;
			this.torrentUploadSlotSpinButton.ClimbRate = 1;
			this.torrentUploadSlotSpinButton.Numeric = true;
			this.table2.Add (this.torrentUploadSlotSpinButton);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table2 [this.torrentUploadSlotSpinButton]));
			w62.TopAttach = ((uint)(3));
			w62.BottomAttach = ((uint)(4));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment4.Add (this.table2);
			this.frame5.Add (this.GtkAlignment4);
			this.GtkLabel11 = new global::Gtk.Label ();
			this.GtkLabel11.Name = "GtkLabel11";
			this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Bandwidth</b>");
			this.GtkLabel11.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel11;
			this.vbox6.Add (this.frame5);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame5]));
			w65.Position = 0;
			this.hbox13.Add (this.vbox6);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vbox6]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			w54.Add (this.hbox13);
			this.scrolledwindow2.Add (w54);
			this.detailNotebook.Add (this.scrolledwindow2);
			global::Gtk.Notebook.NotebookChild w69 = ((global::Gtk.Notebook.NotebookChild)(this.detailNotebook [this.scrolledwindow2]));
			w69.Position = 4;
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Options");
			this.detailNotebook.SetTabLabel (this.scrolledwindow2, this.label13);
			this.label13.ShowAll ();
			this.vPaned.Add (this.detailNotebook);
			this.hPaned.Add (this.vPaned);
			this.vbox1.Add (this.hPaned);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hPaned]));
			w72.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (1F, 0.5F, 0F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.natStatus = null;
			this.hbox4.Add (this.natStatus);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.natStatus]));
			w73.Position = 0;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='statusToolbar'/></ui>");
			this.statusToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/statusToolbar")));
			this.statusToolbar.Name = "statusToolbar";
			this.statusToolbar.ShowArrow = false;
			this.statusToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.statusToolbar.IconSize = ((global::Gtk.IconSize)(1));
			this.hbox4.Add (this.statusToolbar);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.statusToolbar]));
			w74.Position = 1;
			this.alignment4.Add (this.hbox4);
			this.vbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment4]));
			w76.Position = 3;
			w76.Expand = false;
			w76.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 765;
			this.DefaultHeight = 658;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.About.Activated += new global::System.EventHandler (this.OnAboutActivated);
			this.Quit.Activated += new global::System.EventHandler (this.OnQuitActivated);
			this.stopTorrentButton.Activated += new global::System.EventHandler (this.OnStopTorrentActivated);
			this.removeTorrentButton.Activated += new global::System.EventHandler (this.OnRemoveTorrentButtonActivated);
			this.preferences.Activated += new global::System.EventHandler (this.OnPreferencesActivated);
			this.deleteTorrentButton.Activated += new global::System.EventHandler (this.OnDeleteTorrentButtonActivated);
			this.EditColumns.Activated += new global::System.EventHandler (this.OnColumnsActivated);
			this.ShowLabels.Activated += new global::System.EventHandler (this.OnShowLabelsActivated);
			this.ShowDetailedInfo.Activated += new global::System.EventHandler (this.OnShowDetailedInfoActivated);
			this.OpenTorrent.Activated += new global::System.EventHandler (this.OnOpenActivated);
			this.startTorrentButton.Activated += new global::System.EventHandler (this.OnStartTorrentActivated);
			this.NewTorrent.Activated += new global::System.EventHandler (this.OnNewActivated);
			this.Plugins.Activated += new global::System.EventHandler (this.OnPluginsActivated);
			this.ReportBugAction.Activated += new global::System.EventHandler (this.OnReportBugActivated);
			this.gotoTopAction.Activated += new global::System.EventHandler (this.OnPriorityHighest);
			this.gotoBottomAction.Activated += new global::System.EventHandler (this.OnPriorityLowest);
			this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		}
	}
}
